# Generated by Django 5.2 on 2025-04-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the diet plan', max_length=100)),
                ('meal_type', models.CharField(choices=[('VG', 'Vegetarian'), ('NV', 'Non-Vegetarian'), ('VGN', 'Vegan')], help_text='Type of meal (Vegetarian/Non-Vegetarian/Vegan)', max_length=3)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per meal in USD', max_digits=6)),
            ],
        ),
    ]
